sudo: false

language: node_js
node_js: "13.9.0"


cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Windows and Mac
      if: tag IS present
      os: osx
      osx_image: xcode10.1
      script:
        - npm electron-build -mw
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: Deploy linux
      if: tag IS present
      os: linux
      dist: trusty
      script:
        - npm electron-build -l